modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="statscrystal"
version="1.1.0"
displayName="Stats Crystal"
description='Add crystals that can increase your stats.'

[[dependencies.statscrystal]]
modId="forge"
versionRange="[47,)"
mandatory=true

[[dependencies.statscrystal]]
modId="minecraft"
versionRange="[1.20.1,1.21)"
mandatory=true

[[dependencies.statscrystal]]
modId="placebo"
versionRange="[8.6.0,)"
mandatory=true

[[dependencies.statscrystal]]
modId="attributeslib"
versionRange="[1.3.7,)"
mandatory=true